info:
  description: Flext API
  license:
    name: MIT
  title: Flext
  version: 0.1.0
paths:
  /:
    get:
      tags:
      - info
      summary: Get a directory of API paths
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Root'
              example:
                /: Get a directory of API paths
                /info: Get server configuration and version information
                /openapi: Get the OpenAPI specification
                /ping: Ping the client
        '404':
          description: Item not found
  /info:
    get:
      summary: Get server configuration and version information
      tags:
      - info
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info'
              example:
                platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
                machine_name: dev-machine
                python_version: 3.8.10
                api_version: 0.3.0
                database: phetch
                db_version: 10.4.22-MariaDB-1:10.4.22+maria~focal-log
  /openapi:
    get:
      summary: Get the OpenAPI specification
      tags:
      - info
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenApi'
  /ping:
    get:
      tags:
      - info
      summary: Ping the client
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ping'
  /weather/forecast:
    post:
      tags:
      - transactions
      summary: Weather forecast data
      description: A list of administration records
      parameters:
      - in: query
        name: office
        required: false
        schema:
          type: string
          example: description for a field
      - in: query
        name: grid_y
        required: false
        schema:
          type: integer
      - in: query
        name: grid_x
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forecast'
              example:
              - date: '2020-21-11T06:27:00'
                location: 3W
                acct_number: E043045004
                rx_number: '03311143'
                mnemonic: DIAZ5
                admin_dose: 2.5
                admin_dose_unit: MG
                prescriber: ARANAJ
        '400':
          description: No parameters received
openapi: 3.0.2
components:
  schemas:
    Root:
      type: object
      properties:
        path:
          type: object
    Info:
      type: object
      properties:
        python_version:
          type: string
        api_version:
          type: string
        database:
          type: string
        machine_name:
          type: string
        db_version:
          type: string
        platform:
          type: string
    OpenApi:
      type: object
      properties:
        info:
          type: object
        openapi:
          type: string
        paths:
          type: object
        tags:
          type: array
          items:
            type: string
    Ping:
      type: object
      properties:
        packet_transmit:
          type: integer
          example: 1
        rtt_min:
          type: number
          example: 0.016
        rtt_avg:
          type: number
          example: 0.016
        rtt_mdev:
          type: number
          example: 0.0
        packet_duplicate_count:
          type: integer
          example: 0
        packet_duplicate_rate:
          type: number
          example: 0.0
        packet_receive:
          type: integer
          example: 1
        rtt_max:
          type: number
          example: 0.016
        packet_loss_count:
          type: integer
          example: 0
        destination:
          type: string
          example: 192.168.1.77
        packet_loss_rate:
          type: number
          example: 0.0
    Forecast:
      type: object
      properties:
        long:
          type: number
          nullable: true
        forecast:
          type: string
          nullable: true
        end:
          type: string
          format: date-time
          nullable: true
        start:
          type: string
          format: date-time
          nullable: true
        temperature:
          type: integer
          nullable: true
        office:
          type: string
          nullable: true
          maxLength: 3
        timestamp:
          type: string
          format: date-time
          nullable: true
        lat:
          type: number
          nullable: true
        id:
          type: integer
